name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps: 
      - name: my-step
        run: echo "hello world"
      - name: my-step-2
        run: echo "hiii"
   my-job-2:
    runs-on: ubuntu-latest
    needs: my-job
    steps:
      - name: my-task
        run: echo"the task is here if job1 successed"
